##' @title DESeqResVolcano
##' @description This function would plot volcano based on DESeqRes output and save as pdf and png format
##' @param DEGres a dataframe which would be generated by DESeqRes function
##' @param baseName the prefix of output
##' @param outputDir the path of output
##' @param foldChange a dataframe include group information
##' @param adjPvalue the number of colData to split case and control group
##' @return NULL
##' @examples
##' \dontrun{
##' input = createCountPhe()
##' dds = DEseqObj(input[[1]],input[[2]],refLevel="untreated")
##' res = DESeqRes(dds)
##' DESeqResVolcano(res)
##' }
##' @import ggplot2
##' @importFrom grDevices pdf png dev.off
##' @export
##'

DESeqResVolcano = function(DEGres,baseName="Test",outputDir=".",foldChange=1,adjPvalue=0.05){
  #DEGres=res;foldChange=1;adjPvalue=0.05
  log2FoldChange <- padj <- regulate <- NULL
  # p <- ggplot(data = as.data.frame(DEGres),
  #             aes(x = log2FoldChange,
  #                 y = -log10(padj))) +
  #   geom_point(alpha=0.4, size=3.5,
  #              aes(color=regulate)) +
  #   ylab("-log10(Pvalue)")+
  #   scale_color_manual(values=c("red","green", "grey"))+
  #   geom_vline(xintercept=c(-foldChange,foldChange),lty=4,col="black",lwd=0.8) +
  #   geom_hline(yintercept = -log10(adjPvalue),lty=4,col="black",lwd=0.8) +
  #   theme_bw()

  g = ggplot(data=as.data.frame(DEGres),aes(x=log2FoldChange,y=-log10(padj),colour=factor(regulate))) +
    geom_point() +
    geom_hline(yintercept=-log10(adjPvalue),linetype=4)+geom_vline(xintercept=c(-foldChange,foldChange),linetype=4)
  p = g+scale_size_identity()+
    scale_color_manual(values =c("green","black","red"))+ #"green","black","red" is responding to factor(DEres$regulate), which is "Down","Normal","Up"
    xlab("log2(Fold Change)")+ylab("-log10(FDR)")+
    theme_classic()+
    theme(axis.title=element_text(size=15),legend.title = element_text(size=12),legend.text = element_text(size=12),axis.text = element_text(size=rel(1.5)))

  pdf(file=paste0(outputDir,"/",baseName,"_VOLCANO.pdf"),height=6,width = 9)
  print(p)
  dev.off()

  png(filename=paste0(outputDir,"/",baseName,"_VOLCANO.png"),res=300,height = 2000,width=4000,type="cairo")
  print(p)
  dev.off()
}
